## TF 1.x


Статический граф высислений. Сначала строим граф, потом запускаем вычисления в рамках сессии.

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

a = tf.constant([[1.0, 2.0]])
x = tf.placeholder(dtype=tf.float32)
c = tf.Variable([2.])

val = tf.matmul(a, x) + c
grad = tf.gradients(val, x)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run([val, grad], {x: [[3.], [3.]]}))
    print(sess.run([c * 5 + 2]))


[array([[11.]], dtype=float32), [array([[1.],
       [2.]], dtype=float32)]]
[array([12.], dtype=float32)]


## TF 2.x

Динамический граф

In [1]:
import tensorflow as tf

x = tf.Variable([[1., 2.], [3., 4.]], dtype=tf.float32)
z = tf.ones((2, 2))
x ** 2 + z

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2.,  5.],
       [10., 17.]], dtype=float32)>

Использование GPU/TPU/CPU

In [3]:
with tf.device("/cpu:0"):        
    x = tf.constant([[3.], [3.]])
    print(x)    
    
# with tf.device("/gpu:0"):
#     x = tf.constant([[3.], [3.]])
#     print(x)    

tf.Tensor(
[[3.]
 [3.]], shape=(2, 1), dtype=float32)


Вычисление градиента

In [6]:

with tf.GradientTape() as g:
    a = tf.constant([[1.0, 2.0]])
    x = tf.Variable([[3.], [3.]])
    c = tf.constant([2.])
        
    val = tf.matmul(a, x) + c
    print(g.gradient(val, x))

tf.Tensor(
[[1.]
 [2.]], shape=(2, 1), dtype=float32)
